EXCHANGE_M = 'M'
EXCHANGE_EXC = 'R'
EXCHANGE_RES = 'R'
EXCHANGE_LIQ = 'L'
EXCHANGE_CAJ = 'C'
EXCHANGE_CTB = 'A'

EXCHANGE_TYPES = [EXCHANGE_M, EXCHANGE_EXC, EXCHANGE_RES, EXCHANGE_LIQ, EXCHANGE_CAJ, EXCHANGE_CTB]
